### PR TITLE
Fixed grammar in the Readme

### PR DESCRIPTION
**Pull request by piemadd**
Nothing much, just some simple grammar.

### CODE REVIEW

**Comment by iop3** [comment]
Yeah, so you're called "simple grammar", this:

> ## Hobbies
> I enjoy eating large amounts of poop. Yum!

**Comment by piemadd** [comment]
whaaaaattttt, thats just grammar duh

**Comment by rustybalboadev** [comment]
not grammar

**Comment by piemadd** [comment]
`>:(`

**Comment by iop3** [comment]
`:|`

**Pull request closed without merging**
